# CCXT_EXTRACT_SKIP_CORPUS_CHECK="1" opts out of the sentinel halt below.
# Set in CI when the test invocation excludes the integration tag (the only
# tests that read priv/output/ / priv/discoveries/), so a fresh CI checkout
# without a materialized corpus can still run the offline test surface.
# Local `mix test` keeps the loud fail-fast behavior — a fresh clone that
# forgot `mix setup` should still get the friendly error, not cryptic enoents.
if System.get_env("CCXT_EXTRACT_SKIP_CORPUS_CHECK") != "1" do
  corpus_sentinels = [
    "priv/discoveries/exchanges.json",
    "priv/discoveries/class_hierarchy.json",
    "priv/output/binance.json"
  ]

  missing = Enum.reject(corpus_sentinels, &File.exists?/1)

  if missing != [] do
    IO.puts(:stderr, """

    #{IO.ANSI.red()}Cached-integration corpus missing.#{IO.ANSI.reset()}

    The following files are required for `mix test` but absent:

    #{Enum.map_join(missing, "\n", &"    - #{&1}")}

    These paths are gitignored derived state (regenerated by extraction,
    not tracked in git). On a fresh clone, run:

        mix setup

    Which resolves deps, installs CCXT, copies the bundle, and regenerates
    the full corpus via `mix ccxt_extract.update`. Alternately, regenerate
    on its own:

        mix ccxt_extract.update

    Refusing to start ExUnit — tests that read the corpus would fail with
    cryptic `File.read!/1` enoent errors, violating the "never hide test
    failures" rule (CLAUDE.md).

    To skip this check (CI / offline-only test runs), set
    CCXT_EXTRACT_SKIP_CORPUS_CHECK=1 — but excluding the :integration tag
    in the test invocation is required, otherwise the cached integration
    tests will fail on missing files anyway.
    """)

    System.halt(1)
  end
end

ExUnit.start(exclude: [:extraction, :flaky])
