corpus_sentinels = [
  "priv/discoveries/exchanges.json",
  "priv/discoveries/class_hierarchy.json",
  "priv/output/binance.json"
]

missing = Enum.reject(corpus_sentinels, &File.exists?/1)

if missing != [] do
  IO.puts(:stderr, """

  #{IO.ANSI.red()}Cached-integration corpus missing.#{IO.ANSI.reset()}

  The following files are required for `mix test` but absent:

  #{Enum.map_join(missing, "\n", &"    - #{&1}")}

  These paths are gitignored derived state (regenerated by extraction,
  not tracked in git). On a fresh clone, run:

      mix setup

  Which resolves deps, installs CCXT, copies the bundle, and regenerates
  the full corpus via `mix ccxt_extract.update`. Alternately, regenerate
  on its own:

      mix ccxt_extract.update

  Refusing to start ExUnit — tests that read the corpus would fail with
  cryptic `File.read!/1` enoent errors, violating the "never hide test
  failures" rule (CLAUDE.md).
  """)

  System.halt(1)
end

ExUnit.start(exclude: [:extraction])
